server:
  port: 0

spring:
  application:
    name: stock-moex

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
moex:
  stock:
    url: "https://iss.moex.com/iss/engines/stock/markets/shares/securities.xml?iss.meta=off&iss.only=marketdata&marketdata.columns=SECID,BOARDID,SYSTIME,ISSUECAPITALIZATION_UPDATETIME,BID,OFFER,OPEN,LOW,HIGH,LAST"